### ISSUE TITLE
test_randomized possible error?

### ISSUE THREAD

**Issue by meyjac23** [cs540-testers/hw7-tester#1]
Hi there, this is my first time ever using this part of github. I apologize if I am missing something very blatant because I'm not 100% sure how .isclose()is supposed to work. I am failing the test_randomized test at line 90, so I decided to print out the computed and expected matrices to compare visually, and they seem to be nearly the exact same. The only difference being floats vs ints. Is it this difference that is causing this line to fail? Pictures of matrices are attached
<img width="151" alt="Screen Shot 2020-11-08 at 6 08 16 PM" src="https://user-images.githubusercontent.com/43974135/98488253-ae4a4200-21ed-11eb-8273-8d2e92f0aa4e.png">
<img width="446" alt="Screen Shot 2020-11-08 at 6 08 29 PM" src="https://user-images.githubusercontent.com/43974135/98488256-b30ef600-21ed-11eb-87a6-201a3f81f4a5.png">

**Comment by sauprankul** [comment]
Any reason you're using ints? Ints have less precision than floats in this case because they truncate everything after the ones place. You'd falsely declare ties if you use ints.

**Comment by meyjac23** [comment]
Thanks for the quick response! I was just unaware that we were meant to be using floats, but the reasoning makes a lot of sense. I'll make things floats now, thank you
